### ISSUE TITLE
Unable to run on windows

### ISSUE THREAD

**Issue by JohnCashmore** [assemble/generator-assemble#45] opened 2014-05-13 11:33 UTC
Hi is this a known issue? This doesn't run in windows. 

I get the following output

```
Initializing
Command-line options: --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Initializing config...OK

Registering "assemble" local Npm module tasks.
Reading C:\Users\IEUser\test\testing\node_modules\assemble\package.json...OK
Parsing C:\Users\IEUser\test\testing\node_modules\assemble\package.json...OK
Loading "assemble.js" tasks...OK
+ assemble

Registering "grunt-contrib-clean" local Npm module tasks.
Reading C:\Users\IEUser\test\testing\node_modules\grunt-contrib-clean\package.js
on...OK
Parsing C:\Users\IEUser\test\testing\node_modules\grunt-contrib-clean\package.js
on...OK
Loading "clean.js" tasks...OK
+ clean

Registering "grunt-contrib-connect" local Npm module tasks.
Reading C:\Users\IEUser\test\testing\node_modules\grunt-contrib-connect\package.
json...OK
Parsing C:\Users\IEUser\test\testing\node_modules\grunt-contrib-connect\package.
json...OK
Loading "connect.js" tasks...OK
+ connect

Registering "grunt-contrib-watch" local Npm module tasks.
Reading C:\Users\IEUser\test\testing\node_modules\grunt-contrib-watch\package.js
on...OK
Parsing C:\Users\IEUser\test\testing\node_modules\grunt-contrib-watch\package.js
on...OK
Loading "watch.js" tasks...OK
+ watch
Loading "Gruntfile.js" tasks...OK
+ build, default, server

No tasks specified, running default tasks.
Running tasks: default

Running "default" task

Running "build" task

Running "clean" task

Running "clean:0" (clean) task
Verifying property clean.0 exists in config...OK
Files: dist/sitemap.xml -> 0
Options: force=false, no-write=false
Options: force=false, no-write=false
Cleaning dist/sitemap.xml...OK

Running "assemble" task

Running "assemble:pages" (assemble) task
Verifying property assemble.pages exists in config...OK
Files: src/templates/pages/blog.hbs, src/templates/pages/index.hbs -> dist/
Options: layoutdir="", layout="src/templates/layouts/default.hbs", layoutext="",
 partials="src/templates/partials/*.hbs", data="src/data/*.{json,yml}", assets="
dist/assets", ext=".html", flatten, plugins=["assemble-contrib-permalinks","asse
mble-contrib-sitemap"]
Assembling
Steps: 18

Step 1 assembled.
Calling step 2
Validating options
>> >> Current engine: handlebars
Reading ./package.json...OK
Parsing ./package.json...OK

Step 2 assembled.
Calling step 3

Step 3 assembled.
Calling step 4

Step 4 assembled.
Calling step 5
Assembling default layout
src/templates/layouts/default.hbs
src\templates\layouts\default.hbs
Reading src\templates\layouts\default.hbs...OK

Step 5 assembled.
Calling step 6

Step 6 assembled.
Calling step 7

Step 7 assembled.
Calling step 8
Assembling partials

Processing partials...
>> Processing navbar-fixed-top partial
Reading src/templates/partials/navbar-fixed-top.hbs...OK

Step 8 assembled.
Calling step 9

Step 9 assembled.
Calling step 10

Step 10 assembled.
Calling step 11
Assembling data

Processing data...
Reading src/data/site.yml...OK
Reading src/data/site.yml...OK
Parsing src/data/site.yml...OK

Step 11 assembled.
Calling step 12

Step 12 assembled.
Calling step 13

Step 13 assembled.
Calling step 14

Building pages...
Reading blog
assetsPath: dist/assets
DestFile: dist
        srcFile: src/templates/pages/blog.hbs
        destFile: dist/blog.html
        assets: assets
Reading src/templates/pages/blog.hbs...OK
Compiling page blog
Reading index
assetsPath: dist/assets
DestFile: dist
        srcFile: src/templates/pages/index.hbs
        destFile: dist/index.html
        assets: assets
Reading src/templates/pages/index.hbs...OK
Compiling page index
Information compiled

Step 14 assembled.
Calling step 15

Step 15 assembled.
Calling step 16
Reading package.json...OK
Parsing package.json...OK

Step 16 assembled.
Calling step 17

Assembling pages...
{ _page: 'all',
  dirname: 'dist',
  filename: 'blog.html',
  pageName: 'blog.html',
  pagename: 'blog.html',
  basename: 'blog',
  src: 'src/templates/pages/blog.hbs',
  dest: 'dist/blog.html',
  assets: 'assets',
  ext: '.html',
  extname: '.html',
  page: '\n<h1>Posts</h1>\n{{#each posts}}\n  {{md this}}\n{{/each}}\n',
  data: { title: 'Blog', posts: [ 'README.md' ] },
  filePair:
   { src: [Getter],
     dest: 'dist/',
     orig: { src: [Object], dest: 'dist/' } },
  index: 0,
  number: 1,
  first: true,
  middle: false,
  next: 1,
  last: false }
Currentpage: [object Object]
Variables loaded
{ _page: 'all',
  dirname: 'dist',
  filename: 'index.html',
  pageName: 'index.html',
  pagename: 'index.html',
  basename: 'index',
  src: 'src/templates/pages/index.hbs',
  dest: 'dist/index.html',
  assets: 'assets',
  ext: '.html',
  extname: '.html',
  page: '\n<div class="jumbotron">\n  <h1>{{ heading }}</h1>\n  <p>This is a Ass
emble Generator template using <a href="http://getbootstrap.com">Bootstrap</a>.
It includes a large callout called a jumbotron and three supporting pieces of co
ntent. Use it as a starting point to create something more unique.</p>\n  <p><a
href="blog.html" class="btn btn-primary btn-lg" role="button">Learn more &raquo;
</a></p>\n</div>\n',
  data:
   { title: 'Home',
     heading: 'Yo, Assemble!',
     lead: 'Welcome to my blog!' },
  filePair:
   { src: [Getter],
     dest: 'dist/',
     orig: { src: [Object], dest: 'dist/' } },
  index: 1,
  number: 2,
  first: false,
  prev: 0,
  middle: false,
  last: true }
Currentpage: [object Object]
Variables loaded
Writing dist/sitemap.xml...OK
>> Created dist/sitemap.xml
Reading dist/robots.txt...OK
>> Keeping dist/robots.txt
```

Then the dist dir contains 

```
C:\Users\IEUser\test\testing\dist>dir
 Volume in drive C has no label.
 Volume Serial Number is E0CE-337D

 Directory of C:\Users\IEUser\test\testing\dist

05/13/2014  04:30 AM    <DIR>          .
05/13/2014  04:30 AM    <DIR>          ..
05/13/2014  04:18 AM    <DIR>          assets
05/13/2014  04:22 AM                16 robots.txt
05/13/2014  04:30 AM               503 sitemap.xml
               2 File(s)            519 bytes
               3 Dir(s)  126,121,541,632 bytes free

C:\Users\IEUser\test\testing\dist>
```

This is a fresh project not edited by me.

I have this same issue on an existing project also which means i can't hand it over to the windows guys

**Comment by LaurentGoderre** [comment] 2014-05-13 14:22
Which version are you using?

**Comment by JohnCashmore** [comment] 2014-05-13 15:08
I did a fresh install the generator is `Run the Assemble generator (0.4.11)`
and the package.json has

```
{
  "name": "testing",
  "description": "The best project ever..",
  "version": "0.1.0",
  "homepage": "https://github.com/assemble/testing",
  "author": {
    "name": "IEUser",
    "url": "http://github.com/assemble/"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/assemble/testing.git"
  },
  "bugs": {
    "url": "https://github.com/assemble/testing/issues"
  },
  "engines": {
    "node": ">=0.8"
  },
  "scripts": {
    "test": "grunt assemble"
  },
  "devDependencies": {
    "assemble": "^0.4.37",
    "assemble-contrib-permalinks": "*",
    "assemble-contrib-sitemap": "*",
    "grunt": "~0.4.4",
    "grunt-contrib-clean": "~0.5.0",
    "grunt-contrib-connect": "~0.7.1",
    "grunt-contrib-watch": "~0.6.1",
    "load-grunt-tasks": "~0.4.0",
    "time-grunt": "~0.3.1"
  },
  "licenses": [
    {
      "type": "MIT",
      "url": "https://github.com/assemble/testing/blob/master/LICENSE-MIT"
    }
  ],
  "keywords": [
    "assemble",
    "templates",
    "handlebars",
    "site generator",
    "site builder",
    "grunt"
  ]
}
```

**Comment by JohnCashmore** [comment] 2014-05-13 15:10
The machine i tested it on was the win7 ie8 machine from http://modern.ie with a fresh install of node.

**Comment by LaurentGoderre** [comment] 2014-05-13 15:15
Can you post the gruntfile?

**Comment by JohnCashmore** [comment] 2014-05-13 15:18
Sure 

```
/*
 * Generated on 2014-05-13
 * generator-assemble v0.4.11
 * https://github.com/assemble/generator-assemble
 *
 * Copyright (c) 2014 Hariadi Hinta
 * Licensed under the MIT license.
 */

'use strict';

// # Globbing
// for performance reasons we're only matching one level down:
// '<%= config.src %>/templates/pages/{,*/}*.hbs'
// use this if you want to match all subfolders:
// '<%= config.src %>/templates/pages/**/*.hbs'

module.exports = function(grunt) {

  require('time-grunt')(grunt);

  // Project configuration.
  grunt.initConfig({

    config: {
      src: 'src',
      dist: 'dist'
    },

    watch: {
      assemble: {
        files: ['<%= config.src %>/{content,data,templates}/{,*/}*.{md,hbs,yml}'],
        tasks: ['assemble']
      },
      livereload: {
        options: {
          livereload: '<%= connect.options.livereload %>'
        },
        files: [
          '<%= config.dist %>/{,*/}*.html',
          '<%= config.dist %>/assets/{,*/}*.css',
          '<%= config.dist %>/assets/{,*/}*.js',
          '<%= config.dist %>/assets/{,*/}*.{png,jpg,jpeg,gif,webp,svg}'
        ]
      }
    },

    connect: {
      options: {
        port: 9000,
        livereload: 35729,
        // change this to '0.0.0.0' to access the server from outside
        hostname: 'localhost'
      },
      livereload: {
        options: {
          open: true,
          base: [
            '<%= config.dist %>'
          ]
        }
      }
    },

    assemble: {
      pages: {
        options: {
          flatten: true,
          assets: '<%= config.dist %>/assets',
          layout: '<%= config.src %>/templates/layouts/default.hbs',
          data: '<%= config.src %>/data/*.{json,yml}',
          partials: '<%= config.src %>/templates/partials/*.hbs',
          plugins: ['assemble-contrib-permalinks','assemble-contrib-sitemap'],
        },
        files: {
          '<%= config.dist %>/': ['<%= config.src %>/templates/pages/*.hbs']
        }
      }
    },

    // Before generating any new files,
    // remove any previously-created files.
    clean: ['<%= config.dist %>/**/*.{html,xml}']

  });

  grunt.loadNpmTasks('assemble');
  grunt.loadNpmTasks('grunt-contrib-clean');
  grunt.loadNpmTasks('grunt-contrib-connect');
  grunt.loadNpmTasks('grunt-contrib-watch');

  grunt.registerTask('server', [
    'clean',
    'assemble',
    'connect:livereload',
    'watch'
  ]);

  grunt.registerTask('build', [
    'clean',
    'assemble'
  ]);

  grunt.registerTask('default', [
    'build'
  ]);

};
```

**Comment by LaurentGoderre** [comment] 2014-05-13 15:40
Did you just run the generator and ran grunt?

**Comment by LaurentGoderre** [comment] 2014-05-13 15:43
I was able to reproduce. It seems like the task hangs....

**Comment by LaurentGoderre** [comment] 2014-05-13 15:44
It's the permalink plugin that causes the build to hang. @doowb any idea why that could be?

**Comment by LaurentGoderre** [comment] 2014-05-13 16:03
It seems to be an issue specifically with v0.4.x. I downgraded to v0.3.6 and it fixed it.

**Comment by jonschlinkert** [comment] 2014-05-13 16:07
I think it's because of marked.js. This is conjecture, but I've had similar errors from marked on other repos lately. the marked maintainers regularly make breaking changes without bumping the minor version. we'll look into it.

**Comment by LaurentGoderre** [comment] 2014-05-13 16:14
Actually @jonschlinkert it seems specifically an issue with v0.4.1 I upgraded to v0.4.3 and it worked.

The only thing is that the version has issue on npm so I had to install with the following command

```
 npm install https://github.com/assemble/assemble-contrib-permalinks/tarball/v0.4.3
```

**Comment by jonschlinkert** [comment] 2014-05-13 16:17
v0.4.3 of the permalinks lib? okay good to know

**Comment by LaurentGoderre** [comment] 2014-05-13 16:19
@jonschlinkert perhaps the fix would be to fix the npm registry so that it would get v0.4.3 instead of v0.4.1?

**Comment by jonschlinkert** [comment] 2014-05-13 16:29
wait, I'm confused. which package? permalinks doesn't have a v0.4.3 (but that's what is shown in the code snippet you posted). but grunt and assemble both have a v0.4.1 and v0.4.3.

**Comment by LaurentGoderre** [comment] 2014-05-13 16:44
It does: https://github.com/assemble/assemble-middleware-permalinks/releases

Also if you run `npm view assemble-contrib-permalinks versions` v0.4.3 is there but broken.

```
$ npm view assemble-middleware-permalinks versions
npm http GET https://registry.npmjs.org/assemble-middleware-permalinks
npm http 304 https://registry.npmjs.org/assemble-middleware-permalinks

[ '0.4.2',
  '0.4.3',
  '0.5.0',
  '0.5.1',
  '0.5.2' ]
```

**Comment by jonschlinkert** [comment] 2014-05-13 16:52
you're technically showing info for two different projects though. `assemble-contrib-permalinks` is compatible with the current version of Assemble, but `assemble-middleware-permalinks` is only compatible with the un-released versions of Assemble (v0.5.0 and greater).  

this generator should only be using `assemble-contrib-permalinks`. I'll have to pull it down and see what's causing the issue

**Comment by LaurentGoderre** [comment] 2014-05-13 16:59
OOoh you're right, my mistake. Could we push v0.4.3 to npm anyways to fix this issue?

**Comment by doowb** [comment] 2014-05-13 17:03
I think there are a couple of things happening here...
- 1 the issue is probably with a permalinks version > 0.4 because the generator-assemble project uses an assemble version < 0.5.
- 2 the generator-assemble dynamically adds the permalinks middleware if you choose it so it's grabbing the latest version (even though it should be using one < 0.4 as stated on the permalinks readme.

I think the generator-assemble needs to be updated to make sure the plugins/middleware are installed using the correct versions now that we've moved a lot of those to assemble v0.5 and bumped their minor version numbers.

@JohnCashmore I think if you install a different permalinks version compatible with assemble v0.4 it'll work. (This is confusing since it's supposed to be a generator and just work, but the dynamic version stuff complicates it).

`npm install assemble-contrib-permalinks@0.3.6 --save-dev`

**Comment by jonschlinkert** [comment] 2014-05-13 17:04
sorry about this confusion! this is pre-v0.5.0 growing pains! we'll get this resolved asap

**Comment by doowb** [comment] 2014-05-13 17:05
@LaurentGoderre 0.3.6 should probably work since that's the last compatible version with assemble v0.4.x. In any case, I don't think we can push a version lower than the highest to npm since they removed their `--force` option :frowning:

**Comment by LaurentGoderre** [comment] 2014-05-13 17:06
So v0.4.2 and v0.4.3 are not compatible with assemble 4? It looks to me like they're dead version in limbo state

**Comment by jonschlinkert** [comment] 2014-05-13 17:10
> So v0.4.2 and v0.4.3 are not compatible with assemble 4? It looks to me like they're dead version in limbo state

well, just to be clear there is no v0.4.2 or v0.4.3 of assemble-contrib-permalinks. "contrib" being the important part. the versions you are pointing out are from assemble- **middleware** -permalinks. until we upgrade the generator to use Assemble v0.5.0, the generator should only be using "contrib" plugins, not "middlewares".

**Comment by jonschlinkert** [comment] 2014-05-13 17:11
@LaurentGoderre thanks for trying to help resolve this!

**Comment by LaurentGoderre** [comment] 2014-05-13 17:17
@jonschlinkert so the repo was renamed and new versions for assemble 4 were created in the new repo. I'm wondering if we could back-port them to easily solve this problem. Otherwise, those versions are not very helpful

**Comment by JohnCashmore** [comment] 2014-05-13 17:27
Awesome, by the time i drove home 3 of you had looked at the problem and got a solution, awesome work on this and the plugin guys

**Comment by jonschlinkert** [comment] 2014-05-13 17:30
> I'm wondering if we could back-port them to easily solve this problem.

I think there is some confusion about what's going on. The repo on github has no association with the npm package. If you just use what npm has you're in good shape. However, if there _is_ ever need to get a previous version from git you can easily do that as well - but there shouldn't be since npm has the packages we need to solve this. 

> Otherwise, those versions are not very helpful

Correct, at least not to this particular issue.  But they are useful and necessary if you're working on, testing or using Assemble v0.5.0. I think this is easier to solve that it seems at this point, because we're focusing on the wrong things. I don't think permalinks is the cause of this, my gut tells me that you're getting a false-positive from installing the incorrect middleware version - most likely because it's not even getting registered by assemble.

**Comment by LaurentGoderre** [comment] 2014-05-13 17:44
Is it possible that even v0.4.1 is not supposed to work with assemble v4? The way the code is structure is different than other plugins.

**Comment by doowb** [comment] 2014-05-13 17:45
DUH!, I was confusing things too. I had forgotten that npm doesn't redirect the names like github does.

@jonschlinkert is right, I think there's another issue here and it's probably the marked issue we've seen before.

@LaurentGoderre anything after v0.4 for permalinks (contrib or middleware) is for assemble v0.5.

**Comment by jonschlinkert** [comment] 2014-05-13 17:47
yes, what @doowb said! 

> Is it [possible that even v0.4.1 is not supposed to work with assemble v4? The way the code is structure is different than other plugins.

and DUH! on my part too! I bet v0.4.0 and v0.4.1 _do_ use the new plugin signature! which means we need to unpublish those. I'm looking into it now.

**Comment by jonschlinkert** [comment] 2014-05-13 17:47
good thinking @LaurentGoderre!

**Comment by LaurentGoderre** [comment] 2014-05-13 17:54
Oh those big transitions :P

**Comment by jonschlinkert** [comment] 2014-05-13 17:55
lol, indeed. can someone confirm for me just one thing: which tasks are in the generated grunt file? this will tell me a ton about what's happening.

**Comment by jonschlinkert** [comment] 2014-05-13 18:03
k, should be fixed! @LaurentGoderre hit the nail on the head. Apparently we accidentally published assemble-contrib-permalinks using the new plugin signature before renaming to "middleware". This actually emphasizes that we're doing the right thing by renaming - it was just human error. 

please run `npm -g uninstall generator-assemble` then reinstall it. and please reopen if you continue to have problems.

**Closed as completed by jonschlinkert** 2014-05-13 18:03 UTC
